scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.72:9187']

  - job_name: 'cadvisor-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

